### ISSUE TITLE
Bitcoin Core for 0.3.6

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/bitcoin-core-startos#150]
### Service: Bitcoin
This issue is part of our efforts to ensure that the OS is fully ready for the service when 0.3.6 is launched.

**Current Status:**
- [ ] Works Fine
- [x] Partial Issues
- [ ] Doesn't Work

**Description:**
The Bitcoin service is partially working on StartOS 0.3.6, but there are issues with the health checks that need to be addressed. Current observations include:
- Core functionality, including node configuration and syncing, appears stable.
- Health checks are busted.

**Tasks:**
- [ ] Investigate the cause of health check failures.
- [ ] Optimize the health check process to ensure reliable operation.
- [ ] Verify that all aspects of the Bitcoin service are fully operational and stable on StartOS 0.3.6.

**Comment by Dominion5254** [comment]
Bitcoin Core packaging for 0.3.6 is well underway [here](https://github.com/Start9Labs/bitcoind-startos/tree/update/036).

If there are any 0.3.6 compatibility issues (health checks or otherwise) with the latest 0.3.5.x package of bitcoind-startos that would require shipping an update of Bitcoind-startos, I don't think it makes sense to update/fix the 0.3.5.x package. Instead users would just update or install the 0.3.6 version of Bitcoind-startos which would likely be launched alongside 0.3.6.

**Comment by k0gen** [comment]
Thanks for the update on the Bitcoin Core packaging for 0.3.6. Just to clarify, this specific issue you mentioned regarding potential compatibility problems with the 0.3.5.x package of bitcoind-startos is specifically related to Tracking Services Compatibility for StartOS 0.3.6 development.

This issue is part of our efforts to ensure that the OS is fully ready for the service when 0.3.6 is launched. Given this, I agree that there should be no need to update or fix the 0.3.5.x package.
